[workspace]
resolver = "2"
members = [
    "crates/admin",
    "crates/tunnel-server",
    "crates/tunnel-client",
    "crates/gateway",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["david88558855"]
license = "Apache-2.0"
repository = "https://github.com/david88558855/666"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
panic = "abort"